### ISSUE TITLE
7.3 image unable to install java

### ISSUE THREAD

**Issue by SloshBurch** [splunk/docker-splunk#208]
I'm using Splunk's Docker image for developing [DBConnect ](https://splunkbase.splunk.com/app/2686/) solutions. This requires Java.

In images up through the current 7.2.6 image `d0e924f35601`, I've been able to install java 1.8 using the following command as root in a Splunk Enterprise container:

`apt update && mkdir -p /usr/share/man/man1 && apt install default-jre -y && java -version`

As of the 7.3 image `e92c2081a504`, this no longer works. Neither does workarounds such as:
`apt install software-properties-common -y && add-apt-repository ppa:openjdk-r/ppa && apt-get install openjdk-8-jre
`
Notice I'm trying OpenJDK, not Oracle Java. Although I couldn't get either to install.

Steps to reproduce:

1. Create a new docker image. Use either `splunk:splunk/latest` or `splunk/splunk:7.2.6`: `docker run --name java --hostname java -P -d -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=changeme splunk/splunk:latest`
2. Connect to terminal: `docker exec -it java /bin/bash`
3. Switch to root: `sudo su -`
4. Install Java: `apt update && mkdir -p /usr/share/man/man1 && apt install openjdk-8-jre -y && java -version && sudo su - splunk -c "/opt/splunk/bin/splunk restart"`. In the 7.2.6 image, `default-jre` installs Java 1.8. In the 7.3 image, it installs Java 11. So using `openjdk-8-jre`

On the 7.2.6 image, the installation works:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

```
On the 7.3 image you'll now get the error:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openjdk-8-jre
```

Conversely, installing with `default-jre` installs Java 11 but such is incompatible with DBConnect and throws an error such that the DBConnect java task server won't start.

I've also tried `apt install software-properties-common -y && add-apt-repository ppa:openjdk-r/ppa` to no success.

**Comment by arctan5x** [comment]
Hi. You can set the environ variable "JAVA_HOME" as "openjdk:8" and it would install openjdk8 for you automatically.

**Comment by SloshBurch** [comment]
Oh, I see what you mean in the documentation: [](https://splunk.github.io/splunk-ansible/ADVANCED.html#inventory-script)
I think you meant JAVA_VERSION:
`docker run --name java --hostname java -P -d -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=changeme -e JAVA_VERSION=openjdk:8 splunk/splunk:latest`

But no luck:
```
root@java:~# java -version
-bash: java: command not found
root@java:~#  update-alternatives --config java
update-alternatives: error: no alternatives for java
root@java:~# ls -l /usr/lib/
total 92
drwxr-xr-x  5 root root  4096 May  6 00:00 apt
drwxr-xr-x  2 root root  4096 Jun  4 19:23 bfd-plugins
drwxr-xr-x  2 root root  4096 Jun  4 19:23 compat-ld
drwxr-xr-x  3 root root  4096 Mar  8 08:41 dpkg
drwxr-xr-x  1 root root  4096 Jun  4 19:23 gcc
drwxr-xr-x  2 root root  4096 Jun  4 19:23 gnupg
drwxr-xr-x  2 root root  4096 Jun  4 19:23 gnupg2
drwxr-xr-x  2 root root  4096 Jun  4 19:23 gold-ld
drwxr-xr-x  1 root root  4096 Jun  4 19:23 locale
drwxr-xr-x  1 root root  4096 Jun  4 19:23 mime
-rw-r--r--  1 root root   198 Jan 13  2018 os-release
drwxr-xr-x 27 root root 20480 Jun  4 19:23 python2.7
drwxr-xr-x  2 root root  4096 Jan 22 08:53 sasl2
drwxr-xr-x  3 root root  4096 Jun  4 19:23 ssl
drwxr-xr-x  2 root root  4096 Jun  4 19:23 sudo
drwxr-xr-x  4 root root  4096 Jun  4 19:23 systemd
drwxr-xr-x  1 root root  4096 Jun  4 19:23 tmpfiles.d
drwxr-xr-x  2 root root  4096 Jun  4 19:23 valgrind
drwxr-xr-x  1 root root  4096 Jun  4 19:23 x86_64-linux-gnu
```
Same behavior on 7.2.6.

If it matters, I'm not using ansible but rather just direct command line.

I'm open to other ideas.

**Comment by arctan5x** [comment]
Yeah, I meant Java Version. You need to use ansible because we have logic in ansible to install the jdk for you.

I just ran below docker compose yml and found that java was installed correctly.
`services:
  so1:
    image: splunk/splunk:latest
    hostname: so1
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=helloworld
      - DEBUG=true
      - JAVA_VERSION=openjdk:8
    ports:
      - 8000
      - 8089`

`ansible@so1:/$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)`

**Comment by SloshBurch** [comment]
Oh boy. So I will need to learn ansible and get that setup to see. I know our documentation has some material on it.

But nontheless, isn't that a workaround? I was told this issue should be considered a regression since the behavior has changed between versions.

**Comment by arctan5x** [comment]
You don't have to learn anything. Just supplying that JAVA_VERSION should automatically install JAVA in your container. Would you mind posting end to end terminal outputs here? Since the operating system layer didn't change, the functionality to install Java never changed between 7.2.6 vs 7.3.0.

**Comment by SloshBurch** [comment]
I'm not using Ansible. I'm using command line. I have to run out in a minute so I'll need to try tomorrow. But in the interim, I am pretty sure everything you'd be looking for is in the original post. I tried to put all the details but let me know if I missed anything. Up there is the command to start the container and the command I used to install java.

**Comment by arctan5x** [comment]
I think that there is miscommunication. Ansible script is in the container that executes when you start a container. Unless you are specifically turning that layer off, there is that provisioning layer always running when you run the splunk container. Therefore, by the time you exec into the container, there should be Java installed and configured. I just verified it using both 7.3 and 7.2.6 container.

If you are still confused, would be happy to jump on a call and take a look at your issue. Let me know.

**Comment by SloshBurch** [comment]
Oh wow. Less miscommunication and more me just being ignorant. I have been using the Splunk Docker container for a while now and it's come a long way so while familiar with the container, I'm ignorant of the new fun like Ansible. Lemme revert back and read that page in the documentation to get familiar with this and better consider if this is a regression or just my own misuse.

**Comment by SloshBurch** [comment]
Ok, I spent a LOT of time reviewing this and I think there's an issue still.

I've learned about ansible and started using a default.yml successfuly. Yet, I see no option for controlling `JAVA_VERSION`, or an equivalent, with that method. Reference: [default.yml.spec](https://splunk.github.io/splunk-ansible/advanced/default.yml.spec.html#spec).

`JAVA_VERSION `appears to only be available as an environment variable. Reference: [Environment Variables](https://splunk.github.io/splunk-ansible/ADVANCED.html)

So, let's revisit this with the most simple command with three containers: `7.2.6`, `7.3`, `latest`. My conclusions are that the use of the `JAVA_VERSION` environment variable works on the 7.2.6 image but not the 7.3 nor latest images. I ran the following commands to create the containers:

- 7.2.6: `docker run --name 7.2.6 -P -d -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=changeme" -e "JAVA_VERSION=openjdk:8" splunk/splunk:7.2.6`
- 7.3: `docker run --name 7.3 -P -d -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=changeme" -e "JAVA_VERSION=openjdk:8" splunk/splunk:7.3`
- latest: `docker run --name latest -P -d -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=changeme" -e "JAVA_VERSION=openjdk:8" splunk/splunk:latest`

I then waited some time and ran these validation commands:

- 7.2.6: `docker exec -it 7.2.6 /bin/bash -c "java -version"`
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```
- 7.3: `docker exec -it 7.3 /bin/bash -c "java -version"`
```
/bin/bash: java: command not found
```
- latest: `docker exec -it latest /bin/bash -c "java -version"`
```
/bin/bash: java: command not found
```
FWIW, only the 7.2.6 container was still running. The other containers stopped with the last message:
`splunk/splunk:latest" ERROR: Couldn't read "/opt/splunk/etc/splunk-launch.conf" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?`

I saw you ran "docker compose yml" but I understand that means we're creating a new image all together. My goal is to use the existing build image rather than build a new one. Let me know if I misunderstood again.

**Comment by SloshBurch** [comment]
@arctan5x and I are investigating and have found that the Debian version changed between the 7.2.6 and 7.3 image:

**7.2.6** `cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
VERSION_ID="9"
VERSION="9 (stretch)"
```

*7.3* `cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
```

Looks like the Dockerfile for 7.3 uses `base-debian-10` and we think 7.2.6 was `stretch-slim` which was Debian 9.

**Comment by traytonwhite** [comment]
To contribute to this when I try

`docker run -d -p 5000:5000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=pass1234" -e "JAVA_VERSION=openjdk:8" --name javalatest splunk/splunk:latest`

and check `docker logs` for the container, I see the below error:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'openjdk-8-jdk-headless' is available", "warnings": ["Updating cache and auto-installing missing dependency: python-apt", "Could not find aptitude. Using apt-get instead"]}`

**Comment by SloshBurch** [comment]
Yup, same thing as far as I can tell.

**Comment by PaleWooten** [comment]
Hi all,i've got exact same problem and as far as i can get it - due java license change at 16 april 2019, all packages is not available anymore for Debian 10. You still can download it via oracle site after login thougth.

Ive found some guides like that http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

But cant get it work yet.

Any updates on this issue?

**Comment by bb03** [comment]
@PaleWooten We'll be looking into this.  Java will probably need to go through some adjustments.  There might be some new issues as well, or changes to java installation, stemming from this PR https://github.com/splunk/docker-splunk/pull/222 . Please take a look and let us know if you have any comments.

**Comment by arctan5x** [comment]
This issue is addressed by https://github.com/splunk/splunk-ansible/pull/244.

**Comment by PaleWooten** [comment]
@arctan5x ,Hi! Changes already in image,or not? my latest splunk image is still cannot install JAVA

**Comment by bb03** [comment]
@PaleWooten This is not already in the image, it's in the latest develop branch.  When we push a new master, then this will work.  You are welcome to use splunk/splunk:edge to try things out.  Just keep in mind that this version has not gone through rigorous testing and may be unstable in some areas.

**Comment by jeffmeager** [comment]
My testing shows the debian :edge branch is now working to install java on a CLEAN install. It won't however add it into an existing deployment where /var and /etc is redirected. When I create a new :edge deployment mapping back to my old data folders above, it ignores the java install command. I've tried using SPLUNK_UPGRADE=true FWIW to no effect.
In the end I deployed a clean install to get java then stopped the container, replaced my /etc and /var directories and it's working with java and my existing deployment data.

Also to note, the complete issues remains on the redhat branch. I tried a clean :edge-redhat and it wouldn't install java at all.

**Comment by PaleWooten** [comment]
@megajeff75 ,as workaround - maybe just install in clean,and then copy old stuff to etc and var? its pretty dumb way though

**Comment by PaleWooten** [comment]
@bb03 ,ok,i'll try edge image. Can ypu pls tell me when changes will be pushed to splunk:latest?

**Comment by jeffmeager** [comment]
Yep cheers, what I ended up doing and it worked fine. Edited my original post above.

**Comment by PaleWooten** [comment]
Still have problems,even on edge image:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": "apt-get install --no-install-recommends python-apt -y -q",
    "rc": 100,
    "warnings": [
        "Updating cache and auto-installing missing dependency: python-apt"
    ]
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...
Package python-apt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source




STDERR:

E: Package 'python-apt' has no installation candidate



MSG:

E: Package 'python-apt' has no installation candidate

**Comment by PaleWooten** [comment]
Ok,my bad. It was proxy issue.

**Comment by SloshBurch** [comment]
I just tried on the new 8.0 image and something else appears to be up as I can't even su to root to debug.

`[ansible@latest splunk]$ su -
bash: su: command not found`

**Comment by SloshBurch** [comment]
@arctan5x just verified and I can confirm that this is no longer an issue in the 8.0.1 release (perhaps newer even, but not sure).
Leaving the message here for posterity since the closure is otherwise unclear.

**Comment by SloshBurch** [comment]
Hi @arctan5x - did this regress again? On 8.0.1 I can get java installed with the JAVA_VERSION environment variable defined https://splunk.github.io/splunk-ansible/ADVANCED.html but this no longer works on 9.0.1
