### ISSUE TITLE
Latest image does not start with runtime other than docker

### ISSUE THREAD

**Issue by dadux** [splunk/docker-splunk#352]
Hi,

Since the 8.0.3 image, the container fails to start under `containerd` with the following error when running with : 

```ERROR! Specified hosts and/or --limit does not match any hosts```

I believe this is due to this commit https://github.com/splunk/docker-splunk/commit/0ede5cdf86e79a381b14d8a3c2bdb82d41938a44 

I've raised a similar issue with the splunk-ansibe repo, https://github.com/splunk/splunk-ansible/issues/431 . 

Not sure if you'd rather fix it here, or in ansible.

**Comment by nwang92** [comment]
Addressed in the splunk-ansible issue - we're gonna republish `8.0.3` in the coming days with the fix as well.

**Comment by d3vzer0** [comment]
Same issue here, pulled the latest 8.0.3 image but the error still pops up. Has the fix been re-uploaded to Docker hub as well? :) 

PS. Using Podman since Centos/RHEL 8 doesn't really support Docker anymore (?!?). Images are 100% compatible though.

```
[d3vzer0@test-scm-01 splunk]# podman logs -f 4b
WARNING: No password ENV var.  Stack may fail to provision if splunk.password is not set in ENV or a default.yml
ERROR! Specified hosts and/or --limit does not match any hosts
```

**Comment by dadux** [comment]
@d3vzer0 Running in `podman` you might have to fake either a dockerenv by mounting and empty file in`/.dockerenv` or setting a dummy env variable to faking running in Kubernetes by settting the `KUBERNETES_SERVICE_HOST` env variable.

This is the code responsible to detect it's running in Docker : 

https://github.com/splunk/splunk-ansible/pull/433/files#diff-6b53eddb7a76d7bf044b32a0ee84fc58R93

**Comment by d3vzer0** [comment]
@dadux Awesome, thanks! Setting the KUBERNETES_SERVICE_HOST environment seems to solve the issue for now :)

**Comment by dadux** [comment]
@nwang92 - this should probably be documented somewhere, most of the recent linux distribution (redhat, fedora, AWS linux 2, ...) have replaced `docker` , either with `containerd` or `podman` , and not everyone is running Kubernetes.

**Comment by nwang92** [comment]
Got it, I can add some docs around this. 

Our [official support policy](https://github.com/splunk/docker-splunk/blob/develop/docs/SUPPORT.md) doesn't include containerd/crio/podman yet, and we're also lacking a bit with regards to automation around testing against those runtimes. But this is probably a larger conversation we'll be having internally with other groups given that we have other projects in this space now (ex https://github.com/splunk/splunk-operator).

cc @lephino @pogdin @mikedickey
